language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

matrix:
  fast_finish: true

services:
  - mysql

sudo: false

before_script:
  - mysql -e 'create database sabredav'
#  - composer self-update
  - composer install
#  - echo "zend.enable_gc=0" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script:
  - ./bin/phpunit --configuration tests/phpunit.xml
  - ./bin/phpcs  -p --standard=tests/phpcs/ruleset.xml lib/

notifications:
  irc:
    channels:
        - "chat.freenode.net#sabredav"
    on_success: change
    on_failure: change
